// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtzNXTDd9W4mmLVJo9reAFUi0wsNwcQVc',
    appId: '1:661172887323:android:90c43d5c98e7cf18f5bdbe',
    messagingSenderId: '661172887323',
    projectId: 'well-86e95',
    storageBucket: 'well-86e95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMg4MT7ENN6YMsyJ9x8xPtCm2arCQz9Rs',
    appId: '1:661172887323:ios:a011d66178462611f5bdbe',
    messagingSenderId: '661172887323',
    projectId: 'well-86e95',
    storageBucket: 'well-86e95.appspot.com',
    iosClientId: '661172887323-g844166eh8eqck58nh3a2b25d816lqcj.apps.googleusercontent.com',
    iosBundleId: 'com.company.packageName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMg4MT7ENN6YMsyJ9x8xPtCm2arCQz9Rs',
    appId: '1:661172887323:ios:a011d66178462611f5bdbe',
    messagingSenderId: '661172887323',
    projectId: 'well-86e95',
    storageBucket: 'well-86e95.appspot.com',
    iosClientId: '661172887323-g844166eh8eqck58nh3a2b25d816lqcj.apps.googleusercontent.com',
    iosBundleId: 'com.company.packageName',
  );
}
